#!/bin/bash
# Demo script to show the difference between ZIP and Container deployment

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  AWS Lambda Deployment: ZIP vs Container Image                ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ BEFORE: ZIP Package Deployment                                  │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "  📝 SAM Template:"
echo "    Properties:"
echo "      CodeUri: ../lambda/"
echo "      Handler: chat_handler.lambda_handler"
echo "      Runtime: python3.12  ← Defined in Globals"
echo ""
echo "  🔨 Build Command:"
echo "    sam build --use-container"
echo "    └─> Creates temp container"
echo "    └─> Builds dependencies inside"
echo "    └─> Packages as ZIP"
echo "    └─> Discards container"
echo ""
echo "  📦 Deployment Package:"
echo "    ├─ chat_handler.py"
echo "    ├─ anthropic/ (library)"
echo "    ├─ boto3/ (library)"
echo "    └─ [other dependencies]"
echo "    Total: < 250 MB (hard limit)"
echo ""
echo "  ⚠️  Issues:"
echo "    • Limited to 250 MB"
echo "    • Binary compatibility issues possible"
echo "    • Build container not used in production"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ AFTER: Container Image Deployment ✨                            │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "  📝 SAM Template:"
echo "    Properties:"
echo "      PackageType: Image"
echo "    Metadata:"
echo "      Dockerfile: Dockerfile"
echo "      DockerContext: ../lambda/"
echo ""
echo "  📄 Dockerfile:"
echo "    FROM public.ecr.aws/lambda/python:3.12"
echo "    COPY requirements.txt ."
echo "    RUN pip install -r requirements.txt"
echo "    COPY chat_handler.py ."
echo "    CMD [\"chat_handler.lambda_handler\"]"
echo ""
echo "  🔨 Build Command:"
echo "    sam build"
echo "    └─> Builds Docker image"
echo "    └─> Pushes to Amazon ECR"
echo "    └─> Lambda uses this exact image"
echo ""
echo "  🐳 Container Image:"
echo "    AWS Lambda Base (Python 3.12)"
echo "    ├─ System packages"
echo "    ├─ Python runtime"
echo "    ├─ anthropic/ (library)"
echo "    ├─ boto3/ (library)"
echo "    └─ chat_handler.py"
echo "    Total: < 10 GB (generous limit)"
echo ""
echo "  ✅ Benefits:"
echo "    • 10 GB limit (40x larger!)"
echo "    • Perfect binary compatibility"
echo "    • Same container dev → prod"
echo "    • Easier local testing"
echo "    • Layer caching speeds up builds"
echo ""

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  For Users: No Change Required!                               ║"
echo "║  Same command: ./deploy-safe.sh                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
