#!/bin/bash
# Simple one-command deployment script
# Run this after merging the PR: ./quick-deploy.sh [--yes]

set -e

# Parse command line arguments
AUTO_APPROVE=false
for arg in "$@"; do
    if [[ "$arg" == "--yes" || "$arg" == "-y" ]]; then
        AUTO_APPROVE=true
    elif [[ "$arg" == "--help" || "$arg" == "-h" ]]; then
        echo "Usage: $0 [OPTIONS]"
        echo ""
        echo "Quick deployment script"
        echo ""
        echo "Options:"
        echo "  --yes, -y    Skip all interactive prompts (auto-accept defaults)"
        echo "  --help, -h   Show this help message"
        echo ""
        exit 0
    fi
done

echo "🚀 Quick Deploy - CORS Fix"
echo "================================"
if [ "$AUTO_APPROVE" = true ]; then
    echo "  (Running with --yes flag)"
fi
echo ""

# Check we're in the right place
if [ ! -f "backend/infrastructure/template.yaml" ]; then
    echo "❌ Error: Run from repository root"
    exit 1
fi

# Region
REGION="${AWS_REGION:-us-east-2}"
STACK_NAME="prod-coding-copilot"
echo "📍 Using region: $REGION"
echo "📦 Using stack: $STACK_NAME"
echo ""

# Build
echo "🔨 Building Lambda..."
cd backend/infrastructure
sam build --region "$REGION"

# Deploy
echo "📦 Deploying to AWS..."
if [ "$AUTO_APPROVE" = true ]; then
    sam deploy --region "$REGION" --no-confirm-changeset
else
    sam deploy --region "$REGION" --no-confirm-changeset
fi

# Get endpoints
echo ""
echo "📡 Getting endpoints..."
API_ENDPOINT=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --query 'Stacks[0].Outputs[?OutputKey==`ChatEndpoint`].OutputValue' \
  --output text \
  --region "$REGION")

BUCKET_NAME=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --query 'Stacks[0].Outputs[?OutputKey==`FrontendBucketName`].OutputValue' \
  --output text \
  --region "$REGION")

FRONTEND_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --query 'Stacks[0].Outputs[?OutputKey==`FrontendURL`].OutputValue' \
  --output text \
  --region "$REGION")

# Get Lambda function name (auto-generated by CloudFormation)
FUNCTION_NAME=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query 'Stacks[0].Outputs[?OutputKey==`LambdaFunctionArn`].OutputValue' \
  --output text | awk -F: '{print $NF}')

echo "API Endpoint: $API_ENDPOINT"
echo "S3 Bucket: $BUCKET_NAME"
echo "Lambda Function: $FUNCTION_NAME"

# Update frontend
echo ""
echo "🎨 Updating frontend..."
cd ../../frontend
sed -i.bak "s|YOUR_API_ENDPOINT_HERE|$API_ENDPOINT|g" app.js
rm -f app.js.bak

# Deploy frontend
echo "☁️  Uploading to S3..."
aws s3 sync . s3://$BUCKET_NAME/ --delete --region "$REGION"

# Test CORS
echo ""
echo "🧪 Testing CORS..."
CORS_TEST=$(curl -s -X OPTIONS "$API_ENDPOINT" -H "Origin: http://example.com" -H "Access-Control-Request-Method: POST" -I | grep -i "access-control-allow-origin" || echo "")

if [ -n "$CORS_TEST" ]; then
    echo "✅ CORS headers detected!"
else
    echo "⚠️  Could not verify CORS headers (but might still work)"
fi

# Done
echo ""
echo "=========================================="
echo "✅ DEPLOYMENT COMPLETE!"
echo "=========================================="
echo ""
echo "🌐 Frontend URL:"
echo "   $FRONTEND_URL"
echo ""
echo "📡 API Endpoint:"
echo "   $API_ENDPOINT"
echo ""
echo "🎯 Next steps:"
echo "   1. Open the frontend URL in your browser"
echo "   2. Open Dev Tools (F12) → Network tab"
echo "   3. Send a message"
echo "   4. Verify no CORS errors appear"
echo ""
echo "📊 View logs:"
echo "   aws logs tail /aws/lambda/$FUNCTION_NAME --follow --region $REGION"
echo ""
